# Generated by Django 6.0.7 on 2026-07-19 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CEMENT', 'Cement'), ('RET', 'Ret (Sand)'), ('BAJRI', 'Bajri (Gravel/Aggregate)'), ('BRICK', 'Bricks'), ('STEEL', 'Steel'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('unit', models.CharField(choices=[('BAG', 'Bag'), ('TON', 'Ton'), ('CFT', 'Cubic Feet'), ('TROLLEY', 'Trolley'), ('KG', 'Kg'), ('PCS', 'Pieces')], default='BAG', max_length=20)),
                ('current_rate', models.DecimalField(decimal_places=2, help_text='Rate per unit (PKR)', max_digits=12)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=10, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Sale rate per unit (PKR)', max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='stock.customer')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='stock.material')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Purchase rate per unit (PKR)', max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='stock.material')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='stock.supplier')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
